# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: stspublic-ingress
#   namespace: qa
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}, {"HTTPS": 443}]'
#     alb.ingress.kubernetes.io/ssl-redirect: '443'
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:827455137773:certificate/73cb6a20-ca55-496a-8958-642b6857ff93
#     alb.ingress.kubernetes.io/healthcheck-path: /
#     alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
#     alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
#     alb.ingress.kubernetes.io/healthy-threshold-count: '2'
#     alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
#     alb.ingress.kubernetes.io/security-groups: sg-02ea4cfdbcd2f8fa5
#     alb.ingress.kubernetes.io/subnets: subnet-0752e0ccd8ab71075,subnet-0b3cc8554660d8635
# spec:
#   ingressClassName: alb
#   rules:
#   # STSPublic Application
#   - host: nginx.staysuregroup.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: app-service
#             port:
#               number: 8080
